### ISSUE TITLE
Open Definition is a pirated work without proper attribution

### ISSUE THREAD

**Issue by BrucePerens** [okfn/opendefinition#110]
The Open Definition is very obviously derived from the Debian Free Software Guidelines and now with some edits, yes, but it's still quite derivative. Long ago, I complained to you of this fact and submitted a ticket here with the proper attribution text. You chose to waive it off. It's unfortunate that because of politics OSI chose to remove my attribution from the definition, and there is a person taking credit and listed in Wikipedia who had nothing to do with the authorship of the work. I assert, a second time, proper attribution is to "Bruce Perens and the Debian Developers". It just is an awful shame that proponents of Openness are so reluctant to properly attribute other people's work.

**Comment by BrucePerens** [comment]
FYI, my statement of the origin of the work from which you have obviously derived, and various people's participation, is at http://blog.algoram.com/blog/2014/11/24/about-the-creation-of-the-open-source-definition-and-the-debian-social-contract/

**Comment by rgrp** [comment]
@BrucePerens Mike Linksvayer did work on this in relation to the original issue you opened at https://github.com/okfn/opendefinition/issues/56 We're sorry if that still does not address your concerns. Could you suggest a specific location where you still want amendment post that commit about what we need to improve. As stated there we are committed to getting this right and are making best efforts to do so.

**Comment by BrucePerens** [comment]
OK. Sorry, I went over the top there. There is a ton of old politics behind
this that you have nothing to do with. But it seems to still get me steamed.

Anyway, the background, if you care to read it, is at
http://blog.algoram.com/blog/2014/11/24/about-the-creation-of-the-open-source-definition-and-the-debian-social-contract/

The provenance is:

Debian Free Software Guidelines - attribute to Bruce Perens and the Debian
developers.
Open Source Definition - OSI added #10 after I was no longer involved, the
rest of the text remains the same from the Debian verison.
Open Definition - you hopefully know who to credit.

My desire is that my name and that of the Debian developers not disappear
completely.

   Thanks

   Bruce

**Comment by hlainchb** [comment]
@BrucePerens we are committed to getting this right.  I would like to propose that we add the following text to the footer area of the definition right below the final clause of the definition, adapted from @rgrp 's earlier proposal (issue #56):

"The Open Definition was initially derived from the Open Source Definition, which in turn was derived from the original Debian Free Software Guidelines, and the Debian Social Contract of which they are a part, which were created by Bruce Perens and the Debian Developers. Bruce later used the same text in creating the Open Source Definition. This definition is substantially derivative of those documents and retains their essential principles. Richard Stallman was the first to push the ideals of software freedom which we continue."

@BrucePerens Would this adequately address the provenance issue from your perspective?

**Comment by rgrp** [comment]
@hlainchb +1

**Comment by BrucePerens** [comment]
Looks fine.

 Thanks

 Bruce

**Comment by hlainchb** [comment]
Thanks Bruce.

**Comment by mlinksva** [comment]
The attribution addendum text above is live at http://opendefinition.org/od/2.1/en/ and that version will be announced and linked from the home page soon; closing.
