### ISSUE TITLE
Towards an Open Definition clause for law

### ISSUE THREAD

**Issue by ppKrauss** [okfn/opendefinition#114]
Thinking about **law documents** in any country. Example: [law-docs repository of EU-countries](http://eur-lex.europa.eu/n-lex/), [law-docs repo of BR](http://www.lexml.gov.br/), [law-docs repo of UK](http://www.legislation.gov.uk/browse), etc. ... millions of documents (!).

Statutory law documents (acts and any other statutory *"obligation norm"*) usually have not an explicit licence, or  link or icon indicating the kind of licence  (ex. [by-nd link](http://creativecommons.org/licenses/by-nd/4.0/)) of the document... It is implicit by some (usually hidden/unknown)  other law... But we can talk about **"law-doc licences"**, and its terms.  

So, we can imagine that, *democratic countries* use, typically, *Open licences*... The law-doc licence *must* satisfy the Open Definition... "must"?  But is Open Definition 2.0  enought?? 

[In this discussion (**link**)](http://opendata.stackexchange.com/q/5600/1313)  is shown that law (of democratic countries) need **"contamination by citation"**, that is, law-doc lincence needs a permission clause for this mechanism.

**PROPOSAL**:  create a *"law-doc licences"*  task force, first to check or do a survey of concrete law-doc licences, then a discussion about addiction of a new section 2.2.X clause (Acceptable Conditions) in the OpenDefinition, that meets the *"contamination by citation"* principle; and any other adaptation (see below) need for real applications in law repositories of democratic countries.

-----

## Notes, context and rationale

... sorry my english... and... a proposal in this place is valid? (can I post as issue?)...

* *The share-alike (2.2.3) problem*: reuse of law-documents are valid, and is usual some city reuse and adapt law from other city... to transform into a template and reuse, this is a case of share-alike. But a specific law (instance not template) can't be "adapted" (share-alike), because "adaptation" of law is a falsification.

* *The compilation (2.1.5) problem*: perhaps needs the indication of a  minor exception, for law-docs citations.

* "Pay for norm" is a [trade barrier](http://www.academia.edu/8732380/Information_Asymmetries_as_Trade_Barriers_ISO_9000_Increases_International_Commerce) in the case of (example) ISO standards,  and this barrier is amplified when you are in a   development country...  If a law-document cites another document (another law, an ISO, a map,  etc.), the licence must be propagated to the cited document. ... This is the economic rationale for the "contamination by citation" principle...

**Comment by mlinksva** [comment]
If you want a document cited in a law document to automatically be made open by virtue of being cited in a law document, that's not something a copyright license can accomplish. It calls for a new copyright exception, i.e. a change in public policy.

If you want law documents to use a license which prohibits derivatives from citing non-open documents, I really doubt that will be considered opendefinition.org compliant by anyone, nor that it would make sense to alter the definition for this case. Your want calls for another change in public policy, requiring that any new law cite only open documents.

Both public policy changes sound great to me, but will be very difficult to obtain, and can't be mandated by open licenses. Though open license mandates can help get to a world in which the policy changes are more feasible.

Do I misunderstand?

**Comment by ppKrauss** [comment]
@mlinksva Thanks for hosting this kind of discussion (and my something exotic  long explanations). 

Perhaps the first step to discuss with somebody is asking: "hey, do you agree that *'contamination by citation'* is really a democratic need?"
If it is a wrong principle/hypothesis, it is wrong to waste time discussing consequences of the principle.

The second step, I will explain in the PS below, is remember that, for all this discussion, "law-doc license" is an *a priory* choice, not an author's choice.

-----

> If you want a document cited in a law document to automatically be made open by virtue of being cited in a law document, that's not something a copyright license can accomplish. It calls for a new copyright exception, i.e. a change in public policy.

Each country have its public policy, and the intention is not to change it. In some countries it is a [constitutional rule](https://en.wikipedia.org/wiki/Constitution)... The intention is only to create/support a standard description in the form of licence (OpenDefinition can host this standard description).

I say "we can imagine that (...)" because is the only thing that we can do.  The idea of "survey of concrete law-doc licences" is a kind of interpretation and statistical analysis, like many that OKFN do checking transparency of a country.

> If you want law documents to use a license which prohibits derivatives from citing non-open documents,

Not I, but the *democratic principle*... The hypothesis is that: if it not occurs, democracy is not complete.

>  I really doubt that will be considered opendefinition.org compliant by anyone, nor that it would make sense to alter the definition for this case. Your want calls for another change in public policy, requiring that any new law cite only open documents.

Yes, make sense... Perhaps this is another starting point: how to express a *democratic principle*?  

PS: in general, for creative works, the license is something that the author adds, is an author's choice. Law is another kind of work, and the "law-doc license" is not an author's choice, the law-author must only to respect the standard-license of the specific law-system.

I have some difficulty to express with my bad-English, perhaps you can help to translate it into good-English... The point (of the principle) is: a  law that express obligations to the citizens, must make a chance to citizen-obligation-compliance without obligating  citizen to waste money (or time) to access it.  

... If, and only if, it is a valid and universal *democratic principle*, will make sense to include a specialized clause in OpenDefinition, to explore the licence option of full-openness of law-documents.
 
----

OpenDefinition is a "metalicense", not a license... Is difficult to talk about "metathings"... Illustrating use cases of the law-doc specialized licenses:

* in OKFN (and similar) **reports**, to express the kind of openness of the legislation of a country.

* in other type (not countries) of real life democratic communities, like **condominiums**, cooperatives, etc. They also produce "law" and  can do concrete use of  "law-doc licences".

**Comment by BrucePerens** [comment]
I think you could do this with contract law rather than copyright law.
There would have to be contract terms regarding citation that were agreed
to before you could copy or otherwise use the license. It's not clear,
though, that doing this would fit our own definition of "open".

**Comment by ppKrauss** [comment]
@BrucePerens sorry if was confuse, I explaning better at this local Wiki link,
   https://github.com/okfn/opendefinition/wiki/Citation-alike-clauses-of-open-licenses-for-law

> I think you could do this with contract law rather than copyright law.

hum... the focus here are "documents that are the law" (in US they are the Acts)... I never see a  copyright in a law-document ("obligation norms"), only in voluntary norms like ISO... But I am not an expert.

> There would have to be contract terms regarding citation that were agreed
to before you could copy or otherwise use the license. It's not clear,
though, that doing this would fit our own definition of "open".

The "contract" behind of the set of the laws of a country, is the country's Constitution... We not want to change this "contract"  ;-)
... We want only to describe what kind of licence is possible to interpret from it... that is, imagining a standard license used in all law-documents. 
In some  OKFN reports, like [okfn/opendatacensus/legislation](https://github.com/okfn/opendatacensus), we need this imagination (there are free interpretations about access law-documents).

**Comment by BrucePerens** [comment]
>  I never see a copyright in a law-document ("obligation norms"), only in
voluntary norms like ISO... But I am not an expert.

Under the Bern Copyright Convention of sometime in the 1980's, works are
copyrighted by default with all rights reserved. This is a treaty
convention which essentially all countries have accepted.

It used to be that works were in the public domain until copyright was
declared. Now, everything is copyrighted instantly. So, if legal documents
don't have a license attached to them, you can assume it's "All Rights
Reserved", which is the default under the law.

Licenses are contracts. Free Software folks distinguish the Free Software
licenses from contracts because the Free Software licenses do not take away
any rights. But the court would still read all of our licenses as
contracts. There is no other way for the court to process them. Of course
they are interpreted in the framework of the constitution, as well as all
of the applicable law, and all applicable case law.

If you want to make a license that encumbers (don't say "contaminates",
it's pejorative) a work through reference, you would do so by copyrighting
your work, and then offering it with a contract that does take away some
rights in exchange for others. So, it would be different from a Free
Software license and our definition of "Open" in that regard. You would
offer the right to make use of the referred-to work in exchange for the
encumberance that the user would be bound contractually to perform your
specified actions whenever they referred to your document in another
document.

It's probably possible to do this, although it could be *argued* that
someone could refer to a document without actually using it, and that the
copyright would thus not be infringed.

I am not sure, though, that this fits the agenda of any open project.

    Thanks

    Bruce

**Comment by ppKrauss** [comment]
Hi, I was excited, with my "verbose mode" enabled ;-)  Now I will slowly and making some homework to understand all your points in depth... I will reply only one point at a time (I not forgot the rest!)

> Under the Bern Copyright Convention of sometime in the 1980's, works are
copyrighted by default with all rights reserved. (...)

> It used to be that works were in the public domain until copyright was
declared. Now, everything is copyrighted instantly. So, if legal documents
don't have a license attached to them, you can assume it's "All Rights
Reserved", which is the default under the law.

Good points. I think this is what occurs with US law (Acts), but I am from [Civil Law universe](https://en.wikipedia.org/wiki/Civil_law_%28legal_system%29) and perhaps make mistakes about contractual visiuon and contractual *modus operandi* of [Common Law](https://en.wikipedia.org/wiki/Common_law)...  Perhaps a good practice to this discussion, is also to  focus on concrete examples.

The concrete examples show that the assertion *"if legal documents don't have a license attached to them, you can assume it's 'All Rights Reserved'"*, on my interpretation, is false:

* [offcial gpo.gov PDF of US-Constitution](http://www.gpo.gov/fdsys/pkg/GPO-CONAN-1992/pdf/GPO-CONAN-1992-6.pdf): no explicit license there,  assume it's "All Rights Reserved" by default? It is not an "open work"?

* [official PDF of Brazilian's Constitution](http://www2.camara.leg.br/legin/fed/consti/1988/constituicao-1988-5-outubro-1988-322142-normaatualizada-pl.pdf) (and in other [official links](http://www.lexml.gov.br/urn/urn:lex:br:federal:constituicao:1988-10-05;1988))... No explicit license there, and it is not an opinion, I can assert that *it is open*, not copyrighted, is open.

* (aleatory sample) [Brazilian Federal act 12.965 of 2014](http://legis.senado.gov.br/legislacao/ListaTextoIntegral.action?id=248229&norma=267781), no license, but it is not copyrighted, is open.

* (aleatory sample) [Italian act 456 of 1981](http://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:1981-08-06;456), no license, but it is not copyrighted, is open.

Note: in all  examples there are "implicit/hidden" contract (where?) that is equivalent to an "open license". This "implicit license" contract need some "mining work" and some dose of interpretation. 

PS: the "hidden contract" in Brazil starts from an interpretation that all law-documents are "derived works" of the Constitution. Some of Constitution's articles express the "open license":  article 5º (inciso XIV), ensure "everyone access" to legislative information; article 216 (§ 2º) states the "mandatory deductible access" (no pay for law-documents).

**Comment by bluechi** [comment]
Hi everyone,

Many domestic copyright laws exclude official documents, such as
legislations and court decisions, from copyright protection. That's why you
don't need a license to make a copy of the constitution. For example, this
is the text of Article 8(IV) from the translation of the Brazilian
copyright law on WIPO's website
<http://www.wipo.int/wipolex/en/text.jsp?file_id=125393>:

*(8) The following shall be excluded from copyright protection within the
meaning of this Law:*
*...*
*IV. the texts of treaties or conventions, laws, decrees, regulations,
judicial decisions and other official enactments;*

In the US it is a bit different because their law excludes all works
created by the federal government not just legislation.

If the document is "an official enactment" - whether or not it is part of
the legislation document - then it will also be exempt from copyright
protection.

Regards,

Riyadh


On Fri, Jul 17, 2015 at 3:41 PM, Peter <notifications@github.com> wrote:

> Hi, I was excited, with my "verbose mode" enabled ;-) Now I will slowly
> and making some homework to understand all your points in depth... I will
> reply only one point at a time (I not forgot the rest!)
>
> Under the Bern Copyright Convention of sometime in the 1980's, works are
> copyrighted by default with all rights reserved. (...)
>
> It used to be that works were in the public domain until copyright was
> declared. Now, everything is copyrighted instantly. So, if legal documents
> don't have a license attached to them, you can assume it's "All Rights
> Reserved", which is the default under the law.
>
> Good points. I think this is what occurs with US law (Acts), but I am from Civil
> Law universe <https://en.wikipedia.org/wiki/Civil_law_%28legal_system%29>
> and perhaps make mistakes about contractual visiuon and contractual *modus
> operandi* of Common Law <https://en.wikipedia.org/wiki/Common_law>...
> Perhaps a good practice to this discussion, is also to focus on concrete
> examples.
>
> The concrete examples show that the assertion *"if legal documents don't
> have a license attached to them, you can assume it's 'All Rights Reserved'"*,
> on my interpretation, is false:
>
>    -
>
>    offcial gpo.gov PDF of US-Constitution
>    <http://www.gpo.gov/fdsys/pkg/GPO-CONAN-1992/pdf/GPO-CONAN-1992-6.pdf>:
>    no explicit license there, assume it's "All Rights Reserved" by default? It
>    is not an "open work"?
>    -
>
>    official PDF of Brazilian's Constitution
>    <http://www2.camara.leg.br/legin/fed/consti/1988/constituicao-1988-5-outubro-1988-322142-normaatualizada-pl.pdf>
>    (and in other official links
>    <http://www.lexml.gov.br/urn/urn:lex:br:federal:constituicao:1988-10-05;1988>)...
>    No explicit license there, and it is not an opinion, I can assert that *it
>    is open*, not copyrighted, is open.
>    -
>
>    (aleatory sample) Brazilian Federal act 12.965 of 2014
>    <http://legis.senado.gov.br/legislacao/ListaTextoIntegral.action?id=248229&norma=267781>,
>    no license, but it is not copyrighted, is open.
>    -
>
>    (aleatory sample) Italian act 456 of 1981
>    <http://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:1981-08-06;456>,
>    no license, but it is not copyrighted, is open.
>
> Note: in all examples there are "implicit/hidden" contract (where?) that
> is equivalent to an "open license". This "implicit license" contract need
> some "mining work" and some dose of interpretation.
>
> PS: the "hidden contract" in Brazil starts from an interpretation that all
> law-documents are "derived works" of the Constitution. Some of
> Constitution's articles express the "open license": article 5º (inciso
> XIV), ensure "everyone access" to legislative information; article 216 (§
> 2º) states the "mandatory deductible access" (no pay for law-documents).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okfn/opendefinition/issues/114#issuecomment-122252957>
> .
>



-- 
Riyadh Al Balushi

**Comment by mlinksva** [comment]
I'm closing this issue as I don't see anything actionable in the context of opendefinition.org. I'd suggest continuing the conceptual discussion on https://discuss.okfn.org/ and/or getting in touch with the https://en.wikipedia.org/wiki/Free_Access_to_Law_Movement

**Comment by mlinksva** [comment]
ps I meant to start with: good point @bluechi ... IIUC @ppKrauss wants to extend what counts as an official enactment to documents cited by things already considered official enactments. I may misunderstand. :) Feel free to leave a comment about where the conversation is continuing.

**Comment by ppKrauss** [comment]
Error when try to "sign up" (Create New Account) with Github at https://discuss.okfn.org/

> Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?

**Comment by rgrp** [comment]
@ppKrauss can you just sign up normally - discourse sign up may not be working perfectly there atm and we can investigate.

**Comment by ppKrauss** [comment]
@rgrp , @mlinksva, @bluechi and @BrucePerens thanks for attention and good discussion.  The discuss.okfn.org is ok (!), I am trying https://discuss.okfn.org/t/there-are-a-taxonomy-of-law-document-licenses/510

@bluechi, we can continue there?

PS: @BrucePerens I think I will back later to finesh our "in depth" debate, after  a long homework :-)
