### ISSUE TITLE
Legal details for Australia are incorrect

### ISSUE THREAD

**Issue by pietercolpaert** [okfn/opendefinition#146]
According to @ausgoal, the chapter on Australia in http://opendefinition.org/guide/data/ is incorrect and should be removed asap.

@ausgoal: can you elaborate on this?

Source: https://github.com/okfn/opendefinition/issues/145#issuecomment-241246047

**Comment by AusGOAL** [comment]
In brief, the OAKLaw articles are well out of date.  In addition, since Desktop Marketing v Telstra there has been Phone Directories v Telstra, which reversed the earlier decision in Desktop.  There has also been IceTV v NineMSN, and a number of other cases that have all dropped the sweat of the brow test.  

In sum, the content of the guide with regard to Australia refers to cases that are no longer good law, and the other materials you point to are also out of date. 

Perhaps this slidedeck might be of interest.  https://docs.com/ausgoal/6263/odiq-open-data-essentials-law-and-licensing-course

**Comment by pietercolpaert** [comment]
@AusGOAL would you be able to update the page at https://github.com/okfn/opendefinition/blob/gh-pages/guide/data/index.markdown so that it is corrected?

**Comment by AusGOAL** [comment]
I would be, but not today.  In the meantime, I would greatly appreciate if
you would remove the content.  Its misleading to people in Australia and
counter productive to the education and training activity AusGOAL does in
Australia to support open data.

---

_Baden M Appleyard_
_Barrister_

_National Director - AusGOAL_
Mobile: +61(0)459 824 061
LinkedIn https://www.linkedin.com/in/badenappleyard

_AusGOAL_
Visit our Website http://www.ausgoal.gov.au | Like and Share us on
Facebook https://www.facebook.com/AusGOAL | Join our LinkedIn Group
http://linkd.in/oq5L3u | Follow Us on Twitter: @AusGOAL
https://twitter.com/#!/AusGOAL | +1 on Google Plus
https://plus.google.com/u/0/b/108169778015177255341/108169778015177255341/posts/p/pub
|
View our Slides https://docs.com/ausgoal
AusGOAL is the Government and Research Lead of Creative Commons Australia
The contents of this email may be subject to legal professional privilege.
Liability limited by a scheme approved under professional standards
legislation.

**Comment by enyst** [comment]
Wow, that's great to learn, thank you for sharing!

Cc: @rgrp

**Comment by AusGOAL** [comment]
You're welcome.  Keep up the great work on this publication though!  Its much needed!

**Comment by mlinksva** [comment]
Thanks for the report. I deleted the Australia section. Feel free to open a pull request with up to date info.

**Comment by AusGOAL** [comment]
Thanks Mike.

**Comment by rufuspollock** [comment]
@AusGoal when would you be able to provide updated content. My concern here is that we will simply end up with dropped content and never re-add it.

@mlinksva so we don't forget to re-add it shall we open a new issue about reinstating the content properly updated?

@mlinksva + others: one question is whether we want this guide here at all - it might be better having a permanent home at http://opendatahandbook.org/

**Comment by AusGOAL** [comment]
Hi Rufus,

It should be this week,  I have a draft already prepared.

Trust youre well by the way.. we havent spoken in a while.

Cheers

Baden

---

_Baden M Appleyard_
_Barrister_

_National Director - AusGOAL_
Mobile: +61(0)459 824 061
LinkedIn https://www.linkedin.com/in/badenappleyard

_AusGOAL_
Visit our Website http://www.ausgoal.gov.au | Like and Share us on
Facebook https://www.facebook.com/AusGOAL | Join our LinkedIn Group
http://linkd.in/oq5L3u | Follow Us on Twitter: @AusGOAL
https://twitter.com/#!/AusGOAL | +1 on Google Plus
https://plus.google.com/u/0/b/108169778015177255341/108169778015177255341/posts/p/pub
|
View our Slides https://docs.com/ausgoal
AusGOAL is the Government and Research Lead of Creative Commons Australia
The contents of this email may be subject to legal professional privilege.
Liability limited by a scheme approved under professional standards
legislation.

**Comment by rufuspollock** [comment]
@AusGOAL awesome Baden 😄 - yes I'm very well (and hope you are too!).

**Comment by mlinksva** [comment]
@rgrp agree, the material might best live elsewhere, probably best discussed in #145 

@AusGOAL you might want to contribute an update to https://en.wikipedia.org/wiki/Sui_generis_database_right#Australia as well if needed.

**Comment by AusGOAL** [comment]
Hmmm goodness me... yes... ok.

---

_Baden M Appleyard_
_Barrister_

_National Director - AusGOAL_
Mobile: +61(0)459 824 061
LinkedIn https://www.linkedin.com/in/badenappleyard

_AusGOAL_
Visit our Website http://www.ausgoal.gov.au | Like and Share us on
Facebook https://www.facebook.com/AusGOAL | Join our LinkedIn Group
http://linkd.in/oq5L3u | Follow Us on Twitter: @AusGOAL
https://twitter.com/#!/AusGOAL | +1 on Google Plus
https://plus.google.com/u/0/b/108169778015177255341/108169778015177255341/posts/p/pub
|
View our Slides https://docs.com/ausgoal
AusGOAL is the Government and Research Lead of Creative Commons Australia
The contents of this email may be subject to legal professional privilege.
Liability limited by a scheme approved under professional standards
legislation.
