### ISSUE TITLE
Broken second-level markdown headers

### ISSUE THREAD

**Issue by danfowler** [okfn/opendefinition#153]
http://opendefinition.org/licenses/process/

<img width="716" alt="screen shot 2016-09-22 at 11 43 21" src="https://cloud.githubusercontent.com/assets/772616/18755328/c9ef30da-80b9-11e6-95a9-5e0b4acbc6f8.png">

**Comment by mlinksva** [comment]
Thanks @danfowler for filing this #152 and #151! They should all be fixed but feel free to reopen if not and file new issues or pull requests for anything else you find.

**Comment by danfowler** [comment]
👍
