### ISSUE TITLE
A few broken license pages

### ISSUE THREAD

**Issue by justinclift** [okfn/opendefinition#160]
Some of the licenses linked from the [licenses](http://opendefinition.org/licenses/) page have effectively broken links. eg:

 * Against DRM → http://opendefinition.org/licenses/against-drm/ → http://www.freecreations.org/Against_DRM2.html
   * freecreations.org no longer resolves in DNS.
   * Remove it from the list?
* EFF Open Audio License → http://opendefinition.org/licenses/eff-open-audio-licenses
  * This page goes into an endless redirect loop.
  * Maybe point to the wikipedia article instead, which explains its v1.0 then deprecation in reasonable depth?

**Comment by mlinksva** [comment]
For Against DRM, a Wayback Machine link probably makes sense, eg http://web.archive.org/web/20060612204158/http://www.freecreations.org/Against_DRM2.html ... want to make a PR?

The redirect loop is probably a problem only with this site. I'll look into it and fix.

**Comment by justinclift** [comment]
Sure, I can make a PR for the Against DRM one Monday, if you're ok waiting.  I'm not fussed though, so feel free to just fix it directly if you want. :smile:

**Comment by justinclift** [comment]
The EFF Open Audio License page is working again now, thanks. :smile:

The link on that page itself is 404 though. :wink:

**Comment by justinclift** [comment]
Thanks @mlinksva, closing this now as I think they're both adequately taken care of. :smile:
