### ISSUE TITLE
Rename "Indonesian" to "Bahasa Indonesia"

### ISSUE THREAD

**Issue by jfushada** [okfn/opendefinition#179]
In the "The Open Definition In Your Language" section of the website, all languages are written in their own language except for "Indonesian", which is an English word. Would replacing it with "Bahasa Indonesia" be more appropriate?
![image](https://user-images.githubusercontent.com/24749375/38149743-c5fae4a4-3429-11e8-88ad-f702234206bb.png)

**Comment by mlinksva** [comment]
It should be fixed now. Thanks!
