### ISSUE TITLE
Adding the EPL v2 to the list of known licences

### ISSUE THREAD

**Issue by borisbaldassari** [okfn/opendefinition#185]
I would like to add the Eclipse Public Licence v2 to the list of known open licences. I'm not sure how to proceed however.. I can provide all the information needed, could someone please help me with that task?

**Comment by mlinksva** [comment]
If you mean https://opendefinition.org/licenses/ we've generally not listed primarily software licenses as those are extremely well covered at https://opensource.org/licenses/alphabetical (and various other places, that one is just most analogous).

We do have an [approval process](https://opendefinition.org/licenses/process/) for listing licenses but I don't think those involved have capacity to start evaluating software licenses, and the evaluation would be nearly duplicative of existing open source and free software license evaluations.

Closing but feel free to say more if I've misunderstood!
