### ISSUE TITLE
Collect existing license texts here

### ISSUE THREAD

**Issue by rgrp** [okfn/opendefinition#2]
This repo would contain license texts of all licenses we review and approve for archival and reference purposes.

cf https://spdx.org/licenses/

**Comment by rgrp** [comment]
I'm reopening as I think #7 is distinct. Real questions is whether we want texts given other projects collecting texts such as https://spdx.org/licenses/

**Comment by mlinksva** [comment]
I don't see any evidence that anyone wants to do the work. If such a person exists they should probably be encouraged to help with the SPDX texts collection.
