### ISSUE TITLE
Deutschlandlizenz ( Data Licence Germany) 2.0: missing SPDX IDs perhaps not missing?

### ISSUE THREAD

**Issue by GDIAnja** [okfn/opendefinition#216]
From geoportal Lower Saxony we link to http://opendefinition.org/licenses/.

Beneath the headline "Other conformant licenses" there are the two OpenData licenses from Germany:

Data Licence Germany - attribution - version 2.0
Data Licence Germany - Zero - version 2.0

For both licenses there is no SPDX ID as you call it. As I see it, there are IDs for those licenses.

Data Licence Germany - attribution - version 2.0 (SPDX ID may be: dl-by-de/2.0)
Data Licence Germany - Zero - Version 2.0 (SPDX ID may be: dl-zero-de/2.0)

On the German pages they say the licensecode is taken from https://www.dcat-ap.de/def/licenses/.

Maybe somebody could check, whether the dl-by-de/2.0 and dl-zero-de/2.0 fullfill the requirements for SPDX ID. In case this is not true: What has to be done in order to fullfill the requirements?

**Comment by mlinksva** [comment]
@GDIAnja I did not notice this issue when you opened it, apologies for this very late reply. I'd guess they would qualify per https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md

For more about suggesting licenses to be cataloged by SPDX see https://github.com/spdx/license-list-XML/blob/main/CONTRIBUTING.md and the detailed process at https://github.com/spdx/license-list-XML/blob/main/DOCS/new-license-workflow.md

I'm going to close this issue as I don't think there's anything to do in this repo until SPDX ids are assigned, but feel free to @-mention me if I can be of assistance over in spdx/license-list-XML.

Tangentially, the lizenzcodes on https://www.dcat-ap.de/def/licenses/ are quite nonstandard. They should consider migrating the SPDX ids. 😄

**Comment by mlinksva** [comment]
p.s. I suspect the natural SPDX-style ids for these two licenses would be `DL-DE-BY-2.0` and `DL-DE-Zero-2.0`.
