### ISSUE TITLE
Wrong SPDX identifier for older Creative Commons Attribution-ShareAlike licenses

### ISSUE THREAD

**Issue by nicoroeser** [okfn/opendefinition#218]
The [Other conformant licenses](https://opendefinition.org/licenses/#other-conformant-licenses) section in the Conformant Licenses list has a wrong SPDX identifier for the superseded licenses in the Creative Commons Attribution-ShareAlike family. Probably due to a copy-and-paste mistake.

The mentioned SPDX identifier should include `CC-BY-SA-` instead of `CC-BY-`.

**Comment by mlinksva** [comment]
Embarrassing, thanks so much for catching and fixing!
