### ISSUE TITLE
Git repo usable as a submodule for open licenses and json in projects ...

### ISSUE THREAD

**Issue by rgrp** [okfn/opendefinition#27]
Good idea from Mike Linksvayer on list

**Comment by rgrp** [comment]
OK, my view now is that:

1. We keep license "data" stuff in licenses repo https://github.com/okfn/licenses
2. If people want to submodule they will use that

Hence, this issue is WONTFIX and we can close. @mlinksva @hlainchb make sense to you?

**Comment by mlinksva** [comment]
Makes sense to me.

**Comment by rgrp** [comment]
WONTFIX
