### ISSUE TITLE
Review Danish Business Register Terms of Use

### ISSUE THREAD

**Issue by rgrp** [okfn/opendefinition#28]
http://www.cvr.dk/Site/Forms/CMS/DisplayPage.aspx?pageid=128

Used from e.g. http://www.cvr.dk/Site/Forms/CMS/DisplayPage.aspx?pageid=136

**Comment by rgrp** [comment]
@hlainchb shall we take this to the list?

**Comment by mlinksva** [comment]
Link redirects to http://datacvr.virk.dk/data/ not clear where TOS is. Seems stale, closing, re-open if still pertinent.
