### ISSUE TITLE
Updating Open buttons / badges

### ISSUE THREAD

**Issue by rgrp** [okfn/opendefinition#46]
We have had http://opendefinition.org/buttons/ for years and the images are widely used (esp as stickers - see e.g. http://en.wikipedia.org/wiki/Open_data)

Could look to update these and perhaps rebrand as "badges" (now the common term)

* Better way to track use
* Mozilla open badges support (?)
* Updated designs
* Clearer statement that you should pass the requirements
* Open data "inside" for apps using open data

**Comment by mlinksva** [comment]
This is at least partially superseded by #74 and #81 

Closing for now. Things in this issue not addressed by one of the 2 above should probably be addressed in discrete new issues.
