### ISSUE TITLE
Document use of may/must etc

### ISSUE THREAD

**Issue by mlinksva** [okfn/opendefinition#65]
https://lists.okfn.org/pipermail/okfn-discuss/2014-October/010624.html suggests:

If you are soliciting changes, the language throughout seems to use
the words SHALL, MUST NOT, MAY, etc in an RFC2119 sense. If this is
the case, perhaps a note with a reference so that others know how to
interpret these words. If this is not the case, the way in which they
are to be interpreted could be mentioned to stop those of us with a
habit of reading RFCs getting confused.

**Comment by mlinksva** [comment]
I'm leaving open as this sentence may be awkward for translators, since RFC2119 is only defined for English. Sentence:

> The key words "must", "must not", "should", and "may" in this document are to be interpreted as described in [RFC2119](https://tools.ietf.org/html/rfc2119).

A translation could be direct, ignoring that RFC2119 is English only, eg 

> La ŝlosila vortoj "devas", "devas ne", "eble", kaj "eble" en tiu dokumento devas esti interpretita kiel priskribita en [RFC2119](https://tools.ietf.org/html/rfc2119)

Or it could note the English words, perhaps

> La ŝlosila vortoj "devas" (*must*), "devas ne" (*must not*), "eble" (*should*), kaj "eble" (*may*) en tiu dokumento devas esti interpretita kiel priskribita en [RFC2119](https://tools.ietf.org/html/rfc2119)

Or it could link to a translation of RFC2119. A few at https://github.com/ganwell/2119

Or something else. Should we recommend a particular approach for translations?

**Comment by hlainchb** [comment]
@mlinksva can we consider this issue addressed?  It seems the discussion has introduced a related language translation issue, but I would see that as a separate issue since it's not in the original description for this issue.  As the original issue is labelled as as a 2.1 issue I would like to close the original issue if it's been addressed.

**Comment by mlinksva** [comment]
@hlainchb yes closing now. Can deal with translation issue when it comes up.
