### ISSUE TITLE
tighten up 1.3 Open Format

### ISSUE THREAD

**Issue by mlinksva** [okfn/opendefinition#68]
https://lists.okfn.org/pipermail/od-discuss/2014-November/ discussion.

"The work must be provided in a convenient and modifiable form such that there are no unnecessary technological obstacles to the performance of the licensed rights. Specifically, data should be machine-readable, available in bulk, and provided in an open format (i.e., a format with a freely available published specification which places no restrictions, monetary or otherwise, upon its use) or, at the very least, can be processed with at least one free/libre/open-source software tool."

* Is the word "Specifically" helping?
* Data should or must be...?
* Does published specification matter? Does an ad-hoc format that is not restricted by any means make a work non-open? Consider CSV variations.
* Should "or, at the very least" be "and"?
* What does "processed" mean? Possibly something stronger needed. For a long time (probably could argue still, though not my experience) OO.o (now LO) could "process" OOXML files but not well.

Should the clause effectively require that no rents must be paid by anyone, to anyone (patent holder or software vendor) for any use in order for the work to be open, that is comport with " anyone can freely access, use, modify, and share for any purpose (subject, at most, to requirements that preserve provenance and openness)"?

**Comment by wolftune** [comment]
The only outstanding issues I see here are #75 (separate ticket) and whether we clarify what "fully processed means" i.e. without degradation…

**Comment by Stephen-Gates** [comment]
Perhaps "fully processed" could become something like,

An open format *must* allow **works** to be read, performed and written with at least one free/libre/open-source software tool.  

You could add "without degradation" into the sentence.

I thought about adding something about "extracting meaning" but perhaps that's best left to "machine-readable" which also needs to be better defined.

**Comment by wolftune** [comment]
> An open format must allow works to be read, performed and written with at least one free/libre/open-source software tool.

"allow" here is not strong enough. We can't have it just that this is allowed but that there actually *exists* such software that actually can work with the format in real practice.

**Comment by Stephen-Gates** [comment]
@wolftune Agree with your comment on "allow".

Perhaps "fully processed" should align with,
> “Knowledge is open if anyone is free to **access**, **use**, **modify** and **share** it…”

Hence full processing = **access**/read,  **use**/perform/play/display/etc., **modify**, and **share**/write

**Comment by hlainchb** [comment]
@wolftune Also agree with comment on "allow"

@Stephen-Gates +1 on alignment

What are we trying to accomplish with "without degradation" and "fully processed"?  i.e. what are some  examples that are we hoping to eliminate with these words?  Is this about formats like Excel or have we wandered into new territory?

**Comment by Stephen-Gates** [comment]
@hlainchb I thought on degradation was that the **work** *should* be published in a lossless and uncompressed open format so all the original detail is retained. I'm not sure if that's where @wolftune was going?

I guess that the question is how far does the Open Definition go with providing advice on good practice by using "should" statements?
- Maybe a National Budget in PDF is Open but it *should* be published in a format that makes it easy to extract all knowledge (so Excel/CSV is acceptable?).
- A open format specification *should* be documented so others can freely implement it.

You could end up with many of the questions in the ODI Open Data Certificate questionnaire as "should" statements!

What are the rules for including "should" statements?

**Comment by mlinksva** [comment]
@hlainchb @wolftune I missed this 2.1 issue on the call. I'm fine with the current 1.3 text but others may want to review with respect to concerns above.

**Comment by wolftune** [comment]
I think the current draft is good enough to go into 2.1 but want, as always, for the community to have a chance to weigh in before finalizing.

**Comment by hlainchb** [comment]
I agree.  I think the current ODv2.1 draft of 1.3 is good.  The community will have a chance to weigh in as part of the next call for comments before finalization.

**Comment by RouxRC** [comment]
Hi there and thanks a lot @hlainchb for the mailing-list notice.

I seem to have missed the latest updates regarding 1.3 and I'm only catching up now which I feel a bit guilty about... :/

I've been exploring all the latest commits and I'm worried the successive changes have lost in the way both references to bulk access (which was indeed moved to 1.2, but then removed as redundant with "as a whole"), and to machine-readability (which makes me feel like current 1.3 could make now pdf acceptable for data for instance)

In exchange we got this final sentence that sounds a bit unclear and blurred to me : "The work should be provided in the form preferred for making modifications to it."

Although I understand we want to go forward a more global opendefinition than one adressing only data, I feel like it will still be one of the reference documents for data and should then still have clear precisions regarding them.

So with this in mind, I feel like one of the previous formulation of Art 1.3 in the rewriting process was a lot more clear and adressing this matter of expliciting specifically for data these two required features : "Data must be machine-readable and should be provided in bulk."
(cf this version https://github.com/okfn/opendefinition/blob/2766b3fd209799993d5ada55a3e7ac92a5d1115c/source/open-definition-2.1-dev.markdown#13-open-format )

**Comment by Stephen-Gates** [comment]
@RouxRC, I to like the clarity of that version and how it more strongly aligns with the questions used in the Open Data Census. However the "Bulk" requirement is now a must.

**Comment by hlainchb** [comment]
@RouxRC I feel that bulk is adequately covered in 1.2, which is appropriate since it's an access issue.  Would you agree?

If so, then your main issue is machine-readable is now by implication via "can be fully processed with at least one free/libre/open-source software tool".

You also think the final sentence is unclear.

Do I have that right?

**Comment by RouxRC** [comment]
Yes @hlainchb that pretty much covers it:
- as expresses by @Stephen-Gates, even though "bulk" it not written, it is covered and actually now a `must` via "as a whole" in 1.2
- the machine-readability implication is indeed not obvious from `fully processed` imho
- the new final sentence is unclear while i feel like the previous wording giving an explicit requirement of machine-readability for works that are actually data was useful

**Comment by mlinksva** [comment]
This should have been fixed in http://opendefinition.org/od/2.1/en/ if not satisfied feel free to re-open, or better file a new issue addressing what you think needs to be fixed in 2.1.
