### ISSUE TITLE
clarify "fee/libre/open source software tool" in 1.3

### ISSUE THREAD

**Issue by mlinksva** [okfn/opendefinition#75]
In "at least one free/libre/open source software tool" it has been suggested that a definition eg OSD be cited, see discussion at https://lists.okfn.org/pipermail/od-discuss/2014-December/thread.html#1178

Needed for #68

**Comment by wolftune** [comment]
I think this is the only outstanding issue from #68 and there's note there about deferring to FSF/OSI for what qualifies maybe…

**Comment by mlinksva** [comment]
OSD etc cited in intro, no need to reiterate those are what we mean
