### ISSUE TITLE
Apparently it is possible to misread OD 2.0 as allowing DRM'd works. It does not but 2.1 should be harder to misread.

### ISSUE THREAD

**Issue by mlinksva** [okfn/opendefinition#76]
See https://lists.okfn.org/pipermail/od-discuss/2014-December/001186.html

**Comment by hlainchb** [comment]
I am preparing a draft 2.1 now which will include this text.

**Comment by wolftune** [comment]
This seems complete in https://github.com/okfn/opendefinition/blob/master/source/open-definition-2.1-dev.markdown

Can we close this ticket?
