### ISSUE TITLE
Name of the definition in translation

### ISSUE THREAD

**Issue by tarkowski** [okfn/opendefinition#78]
The definition was previously called an "Open Knowledge Definition", currently it's the "Open Definition". Still, most translations use the previous name, and in some cases both - the Czech reads "Open Definition - Definition of Open Knowledge". Guidance on this would be appreciated. In Poland, one concern is that "Open Definition" is a much less clear name with regard to the scope of the definition than "Open Knowledge Definition".

**Comment by mlinksva** [comment]
Closing this as the Polish translation offered in PR #80 is now live.
