### ISSUE TITLE
Translation in Right to Left Languages

### ISSUE THREAD

**Issue by bluechi** [okfn/opendefinition#86]
The translations of right to left languages like Arabic and Hebrew are displayed from left to right and cannot be read properly, something needs to be done about this.

**Comment by mlinksva** [comment]
Thanks for noting, embarrassing and needs to be fixed indeed.

Off the top of my head a variable could be set in the front matter of rtl languages and template could conditionally add dir=rtl attribute in right place if variable set.

I can probably do this next week, but if anyone wishes to submit a patch before, feel free.

**Comment by bluechi** [comment]
Thanks, looking forward to the fix!
