### ISSUE TITLE
Open Format Definition and a Conformant open formats page

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendefinition#93]
I would like to link to a Open Format Definition page with a set of conformant open formats. This would be similar in concept to the Conformant Licenses page.

I would like to link to the Open Format Definition page from the ODI [Open Data Certificate](https://certificates.theodi.org) site. To earn an Open Data Certificate you are asked a [number of questions](https://certificates.theodi.org/overview) including, "Is this data in a standard open format?".  The help text is shown in the image below and the "Read more..." link goes to a UK government site, https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/183962/Open-Standards-Principles-FINAL.pdf 

I think it makes sense to have a global definition that can be leveraged by a number of tools.

Are there plans to work further on the Open Format Definition page beyond updating section 1.3 Open Format in the Open Definition v2.1?

![screenshot 2015-04-20 23 00 05](https://cloud.githubusercontent.com/assets/9379524/7230424/22ea83c2-e7b1-11e4-82b9-c4bc83252518.png)

**Comment by mlinksva** [comment]
I don't think the OFD has been looked at in ages, but this seems like a great use of it. Are there other changes you feel necessary (thanks for the PR removing old links so far)?

Please send a note to od-discuss about your plans, or let me know to do so if you don't feel like joining yet another mailing list.

**Comment by Stephen-Gates** [comment]
I'm happy to propose something to od-discuss. Stay tuned...

**Comment by Stephen-Gates** [comment]
Sent!

**Comment by Stephen-Gates** [comment]
@mlinksva would you like me to draft a new OFD page based on the od-discuss conversation? I would avoid the approving formats concept and just breakdown the meaning of the words and perhaps reference some external lists of open data formats.

**Comment by mlinksva** [comment]
@Stephen-Gates yes that'd be great.

**Comment by Stephen-Gates** [comment]
Draft at http://stephen-gates.github.io/OpenDefinition/index.markdown

Please pardon my lack of GitHub, Markdown and HTML skills. Hopefully the content is useful.

**Comment by Stephen-Gates** [comment]
I've converted the content to a google doc for easier reading https://docs.google.com/document/d/1f7tFyGyZG9FxQT3hK7HkBq-LCCB6DKgNqui4UnlfMe0/edit?usp=sharing

**Comment by mlinksva** [comment]
@Stephen-Gates FWIW I suspect the reason http://stephen-gates.github.io/OpenDefinition/ insn't readering is that the markdown file needs 'front matter' to be parsed, see http://jekyllrb.com/docs/frontmatter/

But in this case it'd be good to work from https://github.com/okfn/opendefinition/blob/gh-pages/ofd/index.markdown

Submit a PR against that, replacing most of it with your new material and we can focus on iterating from there.

**Comment by mlinksva** [comment]
I believe this was addressed by #101 so closing. @Stephen-Gates if not feel free to re-open, or open new issues for the OFD page as needed.
