### ISSUE TITLE
"should... where possible" in 1.3 Open Format definition

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendefinition#95]
"Data must be machine-readable and should be provided in bulk where possible."

"where possible" seems redundant. 

"Data must be machine-readable and should be provided in bulk." seems equivalent. 

From http://www.ietf.org/rfc/rfc2119.txt 
- MUST  -  This word, or the terms "REQUIRED" or "SHALL", mean that the definition is an absolute requirement of the specification.
- SHOULD  -  This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and
carefully weighed before choosing a different course.

**Comment by hlainchb** [comment]
I agree.

**Comment by mlinksva** [comment]
Makes sense to me too. @Stephen-Gates feel free to submit this along with PR for #96 and #97.
