### ISSUE TITLE
2.1 - Section 1.2 - replace "preferably" with "should"

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendefinition#97]
In Section 1.2 of the draft Open Definition 2.1 replace "preferably" with "should"

Current:
"The work must be available as a whole and at no more than a reasonable one-time reproduction cost, preferably downloadable via the Internet without charge."

Proposed:
"The work must be available as a whole and at no more than a reasonable one-time reproduction cost, and *should* be downloadable via the Internet without charge."

**Comment by mlinksva** [comment]
Looks right to me. Do you want to submit a pull request? You should be able to fork and edit on the web directly from https://github.com/okfn/opendefinition/blob/master/source/open-definition-2.1-dev.markdown
