### ISSUE TITLE
Link rot and licensing on PDDL page

### ISSUE THREAD

**Issue by Daniel-Mietchen** [okfn/opendefinition#98]
http://opendefinition.org/licenses/odc-pddl/ is currently tagged as licensed CC BY, which is rather odd for a public domain dedication.

The links in there to 
http://www.opendatacommons.org/odc-public-domain-dedication-and-licence/
and
http://opendefinition.org/licenses/odc-pddl/
are actually not links, and the first of these URLs is broken anyway.

**Comment by mlinksva** [comment]
The CC BY notice in the footer concerns the material on the opendefinition.org site, not the licenses it describes. If this could and should be more clear, suggestion or pull request welcome!
